### ISSUE TITLE
Chrome DevTools Protocol support

### ISSUE THREAD

**Issue by jogibear9988** [SerenityOS/ladybird#39]
What about Chrome DevTools Protocol support?  (https://chromedevtools.github.io/devtools-protocol/)
Would this be possible to implement?

**Comment by jogibear9988** [comment]
Why not? Also for example Firefox supports part of it, for example for puppeteer integration.
And so could some use Chrome Debugger while developing Ladybird. What would be bad to use a standardized protocol for devtools?

**Comment by 89z** [comment]
This is not Chrome or Firefox. Far from it. A big reason this project was created, is because Chrome and Firefox have major problems, from conflicts of interest, to feature bloat. If Ladybird just does everything Chrome does, then its pointless to even create a new browser. Please don't suggest some Chrome feature, unless its critical to browser usage in general.

**Comment by jrasanen** [comment]
> What would be bad to use a standardized protocol for devtools

Is there really a standard dev tools protocol between the browsers, can you link to the standard? I have not heard about Firefox using Chrome dev tools.

I also agree very much with the statement that this should be as independent as possible, not depending on any single browser-specific API or specifications, but rather on RFCs standardized by the WHATWG or W3C.

**Comment by jogibear9988** [comment]
I've not said there is an official standard.

https://firefox-source-docs.mozilla.org/remote/index.html

**Comment by awesomekling** [comment]
Like all projects in the SerenityOS family, Ladybird has [no interest in feature requests from non-contributors](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy). Closing :)
